import React from 'react';
import { IconShield, IconZap } from './Icons';

/**
 * Enterprise Green City ESG & Eco-Impact Scorecard
 * Calculates verified reductions in idling emissions, fuel waste, and traffic congestion.
 */
export default function EcoImpactCard({ bookingCount = 1 }) {
  const count = Math.max(1, bookingCount);

  // Benchmarked Smart City metrics:
  // Pre-booking saves avg 18 minutes searching for street parking.
  // Idling/cruising uses ~0.45L petrol per 18 mins.
  // 1L petrol burning produces ~2.31 kg CO₂ -> 0.45L saves ~1.05 kg CO₂.
  const timeSavedMins = count * 18;
  const hoursSaved = Math.floor(timeSavedMins / 60);
  const remainingMins = timeSavedMins % 60;
  const fuelSavedLitres = (count * 0.45).toFixed(1);
  const co2PreventedKg = (count * 1.05).toFixed(1);

  const getTier = () => {
    if (count >= 5) return { title: 'Urban Eco-Champion', color: '#047857', badge: 'badge-green', icon: '🏆' };
    if (count >= 2) return { title: 'Green Commuter', color: '#0284c7', badge: 'badge-blue', icon: '🌱' };
    return { title: 'Eco Pioneer', color: '#6366f1', badge: 'badge-gray', icon: '⚡' };
  };

  const tier = getTier();

  return (
    <div
      className="card"
      style={{
        background: 'linear-gradient(135deg, #ffffff 0%, #f0fdf4 100%)',
        borderRadius: '16px',
        border: '1.5px solid #a7f3d0',
        padding: '22px 24px',
        marginBottom: '24px',
        boxShadow: '0 4px 12px rgba(16, 185, 129, 0.08)'
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px', marginBottom: '16px' }}>
        <div>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: '700', color: '#059669', textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: '4px' }}>
            🌱 Smart City Sustainability Ledger
          </div>
          <h3 style={{ fontSize: '18px', fontWeight: '800', color: '#0f172a', margin: 0 }}>
            Your UrbanPark Eco-Impact
          </h3>
          <p style={{ fontSize: '13px', color: '#64748b', margin: '2px 0 0' }}>
            Environmental savings generated by reserving spots in advance instead of cruising.
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ fontSize: '20px' }}>{tier.icon}</span>
          <div>
            <div style={{ fontSize: '11px', color: '#64748b', textTransform: 'uppercase', fontWeight: '600' }}>
              Citizen Rating
            </div>
            <div style={{ fontSize: '14px', fontWeight: '800', color: tier.color }}>
              {tier.title}
            </div>
          </div>
        </div>
      </div>

      {/* Metrics Row */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: '14px'
        }}
      >
        <div style={{ background: '#ffffff', padding: '14px', borderRadius: '10px', border: '1px solid #d1fae5' }}>
          <div style={{ fontSize: '11.5px', color: '#059669', fontWeight: '600', textTransform: 'uppercase' }}>
            CO₂ Prevented
          </div>
          <div style={{ fontSize: '22px', fontWeight: '800', color: '#0f172a', marginTop: '2px' }}>
            {co2PreventedKg} <span style={{ fontSize: '13px', fontWeight: '600', color: '#64748b' }}>kg</span>
          </div>
          <div style={{ fontSize: '11px', color: '#64748b', marginTop: '2px' }}>
            Direct tailpipe emissions
          </div>
        </div>

        <div style={{ background: '#ffffff', padding: '14px', borderRadius: '10px', border: '1px solid #d1fae5' }}>
          <div style={{ fontSize: '11.5px', color: '#059669', fontWeight: '600', textTransform: 'uppercase' }}>
            Fuel Conserved
          </div>
          <div style={{ fontSize: '22px', fontWeight: '800', color: '#0f172a', marginTop: '2px' }}>
            {fuelSavedLitres} <span style={{ fontSize: '13px', fontWeight: '600', color: '#64748b' }}>Litres</span>
          </div>
          <div style={{ fontSize: '11px', color: '#64748b', marginTop: '2px' }}>
            Cruising petrol saved
          </div>
        </div>

        <div style={{ background: '#ffffff', padding: '14px', borderRadius: '10px', border: '1px solid #d1fae5' }}>
          <div style={{ fontSize: '11.5px', color: '#059669', fontWeight: '600', textTransform: 'uppercase' }}>
            Cruising Time Saved
          </div>
          <div style={{ fontSize: '22px', fontWeight: '800', color: '#0f172a', marginTop: '2px' }}>
            {hoursSaved > 0 ? `${hoursSaved}h ${remainingMins}m` : `${timeSavedMins} mins`}
          </div>
          <div style={{ fontSize: '11px', color: '#64748b', marginTop: '2px' }}>
            Zero street circling
          </div>
        </div>
      </div>
    </div>
  );
}
